apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=   
  MYSQL_PASSWORD: cGFzc3dvcmQ=        
  MYSQL_USER: d29yZHByZXNz            
